linters-settings:
  gofmt:
    simplify: true

  govet:
    check-shadowing: true

run:
  timeout: 3m
  tests: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: .*
      linters:
        - gocyclo
        - dupl

linters:
  disable:
    - gochecknoglobals
    - gochecknoinits
    - golint
  enable:
    - govet
    - revive
    - gofmt
    - unused
    - errcheck
