services:
  postgres:
    image: postgres:latest
    container_name: geoassistant_postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - fullstack
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: geoassistant_api
    image: geoassistant_api
    build:
      context: .
    ports:
      - 8080:8080
    restart: always
    volumes:
      - .:/usr/src/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fullstack

volumes:
  postgres_data:
  api_volume:

networks:
  fullstack:
    driver: bridge